# paths are relative to src/template_generation/templates/jinja
cmd3-v1:
  path: cmd3/chat_merged_template_v1.jinja
  includes:
    chat_merged_template.jinja:
      path: cmd3/chat_merged_template.jinja

cmd3-v2:
  path: cmd3/chat_merged_template.jinja

cmd3-v3:
  path: cmd3/chat_merged_template_default_thinking.jinja
  includes:
    chat_merged_template.jinja:
      path: cmd3/chat_merged_template.jinja

cmd4-v1:
  path: cmd4/chat_template.jinja
