version: "2"
run:
  modules-download-mode: vendor
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - forbidigo
    - gocritic
    - gocyclo
    - goprintffuncname
    - govet
    - nakedret
    - nilerr
    - nolintlint
    - paralleltest
    - perfsprint
    - revive
    - rowserrcheck
    - staticcheck
    - testifylint
    - thelper
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 300
    forbidigo:
      forbid:
        - pattern: fmt\.Print.*(# Do not commit print statements\.)?
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - unnamedResult
        - paramTypeCombine
        - whyNoLint
      enabled-tags:
        - diagnostic
        - opinionated
        - performance
        - style
      settings:
        hugeParam:
          sizeThreshold: 512
        rangeValCopy:
          sizeThreshold: 512
    gocyclo:
      min-complexity: 100
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/cohere-ai/melody
  exclusions:
    generated: lax
    paths:
      - .github/
