from __future__ import annotations

class PyFilterOptions:
    def __init__(self) -> None: ...
    def cmd3(self) -> PyFilterOptions: ...
    def cmd4(self) -> PyFilterOptions: ...
    def cmd5(self) -> PyFilterOptions: ...
    def rag(self) -> PyFilterOptions: ...
    def multi_hop(self) -> PyFilterOptions: ...
    def search_query(self) -> PyFilterOptions: ...
    def with_chunk_size(self, size: int) -> PyFilterOptions: ...
    def with_left_trimmed(self) -> PyFilterOptions: ...
    def with_right_trimmed(self) -> PyFilterOptions: ...
    def with_inclusive_stops(self, stops: list[str]) -> PyFilterOptions: ...
    def with_exclusive_stops(self, stops: list[str]) -> PyFilterOptions: ...
    def stream_tool_actions(self) -> PyFilterOptions: ...
    def stream_processed_params(self) -> PyFilterOptions: ...
    def stream_non_grounded_answer(self) -> PyFilterOptions: ...
    def no_tools(self) -> PyFilterOptions: ...
    def cofl_decode_xml_text(self, enabled: bool) -> PyFilterOptions: ...
    def cofl_nested_xml(self, enabled: bool) -> PyFilterOptions: ...
    def start_in_answer(self) -> PyFilterOptions: ...
    def remove_token(self, token: str) -> PyFilterOptions: ...
    def with_message_history(
        self,
        messages: list[dict] | None = None,
        documents: list[dict] | None = None,
    ) -> PyFilterOptions:
        """Configure the parser with the `messages` and `documents` that
        will be rendered into the prompt, so it can resolve citation
        indices back to their original document identifiers.

        `messages` and `documents` accept the same shapes used for
        `render_cmd3` / `render_cmd4`. Either argument may be omitted or
        passed as `None` to default to an empty list.

        Best-effort by design: template-shape mistakes (missing
        `tool_call_id`, empty/duplicate ids, `tool_calls` on a
        non-`chatbot` role) do not raise here — that's the renderer's
        job. Only argument deserialisation failures raise `ValueError`.
        """
        ...

class Source:
    tool_call_index: int
    tool_result_indices: list[int]
    document_ids: list[str]

class FilterCitation:
    start_index: int
    end_index: int
    text: str
    sources: list[Source]
    is_thinking: bool

class SearchQueryDelta:
    index: int
    text: str

class AccumulatedToolCall:
    index: int
    id: str
    name: str
    arguments: str

class FilterAggregatedResult:
    content: str | None
    reasoning: str | None
    tool_calls: list[AccumulatedToolCall]
    citations: list[FilterCitation]
    search_queries: list[SearchQueryDelta]

class PyFilter:
    def __init__(self, options: PyFilterOptions) -> None: ...
    @staticmethod
    def cmd3(chunk_size: int | None = None) -> PyFilter: ...
    @staticmethod
    def cmd4(chunk_size: int | None = None) -> PyFilter: ...
    @staticmethod
    def cmd5(chunk_size: int | None = None) -> PyFilter: ...
    def write_decoded(self, decoded_token: str) -> FilterAggregatedResult: ...
    def flush_partials(self) -> FilterAggregatedResult: ...
    def process_full(self, token_strings: list[str]) -> FilterAggregatedResult: ...
    def process_full_text(self, text: str) -> FilterAggregatedResult: ...
    def classify_content_chunks(self, token_strings: list[str]) -> list[bool]: ...

def render_cmd3(config: dict) -> str: ...
def render_cmd4(config: dict) -> str: ...
def render_cmd5(config: dict) -> str: ...
